spring.application.name=dc_fin_soft
spring.datasource.url=jdbc:postgresql://devwmu_dev:RNILP3jJ6v-gZO1KQsm5tmzUWNr0y4dao1N0B6VhFRQ@localhost:3766/devclub_dev_db1
spring.datasource.username=devwmu_dev
spring.datasource.password=RNILP3jJ6v-gZO1KQsm5tmzUWNr0y4dao1N0B6VhFRQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialext.PostgreSQLDialect