spring.application.name=dc_fin_soft
spring.datasource.url=jdbc:postgresql://localhost:3766/devclub_dev_db1
spring.datasource.username=devwmu_dev
spring.datasource.password=RNILP3jJ6v-gZO1KQsm5tmzUWNr0y4dao1N0B6VhFRQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/finance_doc.html
# uncomment this line if we want to sort by HTTP method
# springdoc.swagger-ui.operations-sorter=method 